spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:ad_engine_dev}
    username: ${POSTGRES_USER:gasolinera_dev}
    password: ${POSTGRES_PASSWORD:dev_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    vault:
      enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# Configuración de desarrollo
logging:
  level:
    com.gasolinerajsm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
