server:
  port: 8084

spring:
  application:
    name: ad-engine
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:puntog}
    username: ${POSTGRES_USER:puntog}
    password: ${POSTGRES_PASSWORD:changeme}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

  cloud:
    vault:
      enabled: true
      scheme: http
      host: localhost
      port: 8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:myroottoken}
      kv:
        enabled: true
        backend: secret
        profile-separator: /
        default-context: application
        application-name: ${spring.application.name}

app:
  admob:
    fallback_ad_url: ${FALLBACK_AD_URL}

jwt:
  secret: ${JWT_SECRET}

# --- OpenTelemetry Tracing Configuration ---
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
