spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:auth_service_dev}
    username: ${POSTGRES_USER:dev_user}
    password: ${POSTGRES_PASSWORD:dev_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

# Configuración de desarrollo
logging:
  level:
    com.gasolinerajsm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: dev-secret-key-for-development-only
    refreshSecret: dev-refresh-secret-key-for-development-only
  auth:
    admin-email: admin@gasolinerajsm.com
    admin-password: admin123
    advertiser-email: advertiser@gasolinerajsm.com
    advertiser-password: advertiser123
