openapi: 3.0.3
info:
  title: Coupon API
  version: v1
  description: API for Coupon service
servers:
  - url: http://localhost:8086
    description: Local development server
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "UP"