spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:station_service_dev}
    username: ${POSTGRES_USER:gasolinera_dev}
    password: ${POSTGRES_PASSWORD:dev_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false # Deshabilitar Flyway temporalmente
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    vault:
      enabled: false

# Configuración de desarrollo
logging:
  level:
    com.gasolinerajsm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
