image:
  repository: <YOUR_ECR_REPO_URL>/raffle-service
  tag: "latest"

service:
  port: 8080

env:
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: puntog-secrets
        key: POSTGRES_HOST
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: puntog-secrets
        key: REDIS_URL
