
CREATE TABLE users (
    id UUID PRIMARY KEY,
    phone_number VARCHAR(255) UNIQUE NOT NULL,
    roles TEXT[] NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
