server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: redemption-service
          uri: lb://redemption-service
          predicates:
            - Path=/redeem/**
        # Add other routes as services are created
        # - id: station-service
        #   uri: lb://station-service
        #   predicates:
        #     - Path=/stations/**
    vault:
      enabled: true
      scheme: http
      host: localhost
      port: 8200
      authentication: TOKEN
      token: ${VAULT_TOKEN:myroottoken}
      kv:
        enabled: true
        backend: secret
        profile-separator: /
        default-context: application
        application-name: ${spring.application.name}

# Service discovery for docker-compose will use container names
# For Kubernetes, this would use service names e.g., http://auth-service:8081
auth-service:
  uri: http://auth-service:8081
redemption-service:
  uri: http://redemption-service:8082
ad-engine:
  url: http://ad-engine:8083 # Assuming ad-engine runs on port 8083
redemption-service:
  url: http://redemption-service:8084 # Assuming redemption-service runs on port 8084