server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600

      # Circuit breaker configuration
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        pool:
          max-connections: 100
          max-idle-time: 30s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://auth-service:8081}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://auth-service:8081/.well-known/jwks.json}

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      ad-engine-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      raffle-service-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    com.gasolinerajsm.apigateway: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# Service URLs (can be overridden by environment variables)
services:
  auth-service:
    url: ${AUTH_SERVICE_URL:http://auth-service:8081}
  coupon-service:
    url: ${COUPON_SERVICE_URL:http://coupon-service:8084}
  station-service:
    url: ${STATION_SERVICE_URL:http://station-service:8083}
  ad-engine:
    url: ${AD_ENGINE_URL:http://ad-engine:8082}
  raffle-service:
    url: ${RAFFLE_SERVICE_URL:http://raffle-service:8085}

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

services:
  auth-service:
    url: http://localhost:8081
  coupon-service:
    url: http://localhost:8084
  station-service:
    url: http://localhost:8083
  ad-engine:
    url: http://localhost:8082
  raffle-service:
    url: http://localhost:8085

logging:
  level:
    root: INFO
    com.gasolinerajsm.apigateway: DEBUG

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.gasolinerajsm.apigateway: INFO
  file:
    name: /var/log/api-gateway.log

management:
  endpoint:
    health:
      show-details: when-authorized
