image:
  repository: <YOUR_ECR_REPO_URL>/api-gateway
  tag: "latest"

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.gasolinera-jsm.com
      paths:
        - path: /
          pathType: Prefix

env:
  - name: POSTGRES_HOST
    valueFrom:
      secretKeyRef:
        name: puntog-secrets
        key: POSTGRES_HOST
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: puntog-secrets
        key: REDIS_URL
